// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.25.0

package db

import ()

type Account struct {
	ID        int64  `json:"id"`
	FirstName string `json:"first_name"`
	LastName  string `json:"last_name"`
	UserName  string `json:"user_name"`
	Password  string `json:"password"`
}

type Todo struct {
	ID        int64  `json:"id"`
	AccountID int64  `json:"account_id"`
	Title     string `json:"title"`
	Time      string `json:"time"`
	Date      string `json:"date"`
	Complete  string `json:"complete"`
}
